### PR TITLE
Update imgur_show_user_stats_light.user.js

### PR DESCRIPTION
**Pull request by svarvsven**
Not sure if you like this - its just an idea, but I would really be happy with those links added. Actually I would be happy to get another script for http://community.imgur.com that also add the same 3 links so its easy to get back into imgur with any profile.

Interesting with all the new statistics you managed to get. Keep up the good work! :-)

### CODE REVIEW

**Comment by SleepProgger** [comment]
Thank you for the pull request.
I like the general idea, especially the linking between ic and imgur.
I won't merge this request but will implement the features with minor changes:  
- The link to the albums should integrate seamless into "comments/submitted images - button area".  
  Never really realized it wasn't there.  
- The ic link is only necessary on imgur and the imgur link only on ic, i guess.?

I guess the best place for this info on ic is this popup box when you click on a username and the profile, or what do you think ?  
Maybe it is possible to use the same userscript on ic and imgur, i'll investigate that.

**Comment by SleepProgger** [comment]
I committed a version where the numbers are now links to the relevant pages (albums, galleries, ..).  
Also there is now a link to the users ic profile, or a "file not found" page if the user is not registered.
I really don't like this, but didn't found a reliable way to check if the user is registered at ic. 
One could (for example) request https://community.imgur.com/users/{username}.json for this, but the server does not allow cross domain requests.

So the only way i see ATM is using greasemonkeys ajax function which allows for cross domain requests. But this would mean neither bookmarklet support nor other browsers(i guess).

Please feel free to share your ideas and thoughts about this.
I'll keep this pull request open for now.

**Comment by svarvsven** [comment]
Ah ok, sounds cool. I will have a look at it.

**Comment by SleepProgger** [comment]
I committed a userscript showing the imgur stats at ic
https://github.com/SleepProgger/imgur_userscripts/blob/master/scripts/ic_imgur_stats_light.user.js

The smaller username in the user profile is now a link to the imgur profile, plus hovering over it gives you the stats like in the imgur_stats script.

I don't quite like the design and placement. Maybe you have an idea to make it a little bit better fitting into the ic layout ?

**Comment by SleepProgger** [comment]
I'll close this one request now. OFC: feel free to open new pull requests/tickets.

**Pull request closed without merging**
